### ISSUE TITLE
Server Push

### ISSUE THREAD

**Issue by caniszczyk** [twitter/CocoaSPDY#1]

**Comment by plivesey** [comment]
Is there any update on this? It looks like @blakewatters work was abandoned?

**Comment by kgoodier** [comment]
I just issued a pull request (https://github.com/twitter/CocoaSPDY/pull/136) for server push support based on work I did at the beginning of the year, which was itself based on work done by @blakewatters et al (https://github.com/twitter/CocoaSPDY/pull/59). 

This is fundamentally different from the approach taken in https://github.com/twitter/CocoaSPDY/pull/59 by not exposing as much to the app. This means the app does not have to be aware of SPDY sessions and does not have to implement and register a custom delegate. Instead, the app uses the standard NSURL system for hooking up to pushed streams, with an NSNotification posted whenever new pushed requests are received.

You could still use a long-lived NSURLRequest and receive multiple push requests associated with it. This new implementation _should_ provide all the same functionality that @blakewatters needed in his implementation, but will obviously require some code changes.

**Comment by kgoodier** [comment]
https://github.com/twitter/CocoaSPDY/pull/136 merged. Please open new issues to discuss future additions, changes, questions on use, etc.
