### ISSUE TITLE
Using SPDY, Is it possible to use UDT as the transport layer.

### ISSUE THREAD

**Issue by Rajitha-Gangam** [twitter/CocoaSPDY#101]
Hi,
SPDY uses TCP as the underlying transport layer,
Is it possible to use UDT as the underlying transport layer.
If possible, Please provide the sample code.

Thanks

**Comment by kgoodier** [comment]
From a technical standpoint of CocoaSPDY, it is not possible today. However, SPDYSocket.m/.h, which manages both queueing/reading/writing of data, and the TCP stream I/O, exposes a fairly small API surface to the other layers. It could be swapped out with a UDT-based version, I suppose.
