### ISSUE TITLE
Using SPDY, Is it possible to communicate HTTP with UDP 

### ISSUE THREAD

**Issue by Rajitha-Gangam** [twitter/CocoaSPDY#104]
I want to communicate HTTP via UDP instead of TCP.
Is it possible using SPDY?
If possible, Please provide the steps how to do ? or provide some sample code.

**Comment by jpinner** [comment]
Duplicate of #101

**Comment by kgoodier** [comment]
An additional note: in addition to what's discussed in https://github.com/twitter/CocoaSPDY/issues/101, you would also have to provide reliable, in-order delivery of packets on top of UDP (assuming you didn't mean UDT or QUIC or something).
