### ISSUE TITLE
Unexpected end of stream

### ISSUE THREAD

**Issue by fdematos** [twitter/CocoaSPDY#21]
Hi,

First I want to thanks you for providing this library.

Our server is setup to use SPDY but anytime I try to call a webservice, I got an error.

Logs are : 

SPDY [WARNING] loaded DEBUG build of SPDY framework
SPDY [INFO] register origin: <SPDYOrigin: 0xc488c70>
SPDY [DEBUG] origin registered: <SPDYOrigin: 0xc488c70>
SPDY [INFO] start loading https://XXXXXXXX/sts/SecurityTokenService/UT
SPDY [INFO] session connecting to <SPDYOrigin: 0xc7b1910>
SPDY [DEBUG] session using TLS
SPDY [DEBUG] sent client SETTINGS
SPDY [DEBUG] sent WINDOW_UPDATE.0 (+10420224)
SPDY [DEBUG] sent SYN_STREAM.1
SPDY [DEBUG] sent DATA.1! (1161)
SPDY [DEBUG] socket connected to XXXXXXX
SPDY [DEBUG] socket read[0](173)
SPDY [DEBUG] received DATA.1013478509 (165)
SPDY [DEBUG] sent RST_STREAM.1013478509
SPDY [DEBUG] socket scheduling read[1](0:0)
SPDY [WARNING] session connection error: Error Domain=SPDYSocketErrorDomain Code=6 "Unexpected end of stream." UserInfo=0xc79eb40 {NSLocalizedDescription=Unexpected end of stream.}
SPDY [INFO] session connection closed
SPDY [INFO] stop loading https://XXXXXXXX/sts/SecurityTokenService/UT

Do you have any idea of the reason or causes of this problem.

Thanks in advance.

**Comment by RomanTruba** [comment]
I have just same issue. Is it client or server side issue?
Is it possible to debug?
