### ISSUE TITLE
Having trouble linking the "framework" in iOS app

### ISSUE THREAD

**Issue by danielctull** [twitter/CocoaSPDY#31]
Hey there, I've been trying for a while to get the lipo'd framework linking with my iOS app to try SPDY out with it.

I have created an example project showing how I'm trying to set it up, which is at https://github.com/danielctull-tests/SPDY-Linking-Test

My setup is as such:
* I have my app project in git and added SPDY as a submodule
* In my app's project, I have added the SPDY project as a sub-project
* Add SPDY.framework to "Target Dependencies"
* Add SPDY.framework to "Link Binary with Libraries"

(In my experience, libraries don't usually need step 3, you just link them and they'll build, but this framework does.)

I'm running into a problem that says:

>clang: error: no such file or directory: '/Users/danielctull/Library/Developer/Xcode/DerivedData/SPDY_Linking_Test-ccbjivxaodzvgebftyllogvlhldk/Build/Products/Debug/SPDY/SPDY'

I've tried adding the location the SPDY.framework gets build to (Debug vs Debug-iphonesimulator) to the libraries and frameworks search paths in my app target's settings, but this doesn't help. 

Unfortunately, while I've done a lot of work with normal static libraries and linking them etc, I'm not 100% how Xcode links, and where it expects to find, fake frameworks like this.

Any advice would be great.

**Comment by kgoodier** [comment]
The latest work on the 'develop' branched has changed the build process and added static targets. It should make it easier to incorporate CocoaSPDY now.
