### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by nutinshell** [twitter/CocoaSPDY#33]
I found CocoaSPDY don't use proxy setting of the system, can you add the proxy support?

**Comment by didipluto** [comment]
+1

**Comment by zhuangsirui** [comment]
I think it's a good idea to support PAC. Please! That's very important! +1

**Comment by kgoodier** [comment]
Support was added in https://github.com/twitter/CocoaSPDY/pull/92. PAC files are supported.
