### ISSUE TITLE
SystemConfiguration.framework might need to be manually added in project config

### ISSUE THREAD

**Issue by austinzheng** [twitter/CocoaSPDY#98]
Hi,

I cloned the CocoaSPDY repo, made a few changes to accommodate my self-signed test server, and built the project, resulting in a framework. I then built a very simple iOS test app in Xcode 6.1.1, copied the framework into my project directory, and added the framework in "Link Binary with Libraries".

My project built and ran fine on the newer iOS simulators, but wouldn't successfully link when built targeting a iPhone 4S or one of the older simulators. It turned out I needed to manually add the 'SystemConfiguration' framework as well. After that it worked fine.

This isn't a bug report or a complaint about outstanding issues, but rather a suggestion that the instructions in the README mention the possible need to link the additional system framework. If nobody objects I can submit a pull request.

Thanks,
Austin

**Comment by kgoodier** [comment]
Thanks Austin. Please do submit a pull request!
